
package ec.edu.espe.view;

import ec.edu.espe.Controller.CustomerController;
import ec.edu.espe.Controller.ProjectController;
import ec.edu.espe.model.Customer;
import ec.edu.espe.model.Project;
import ec.edu.espe.model.ProjectStatus;
import java.awt.SystemColor;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.List;
import java.util.Random;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Dennis Paucar
 */
public class AddProjectFrm extends javax.swing.JFrame {

    private CustomerController customerController= new CustomerController();
    private ProjectController projectController = new ProjectController();
    
    
    
    private Customer customer;
    private MainMenu mainMenu;
    
    public AddProjectFrm() {
        initComponents();
        buttonGroup1 = new ButtonGroup();
        buttonGroup1.add(rbtnCustomerOptionYes);  
        buttonGroup1.add(rbnCreateNewCustomer); 
        jPanel3.setVisible(false);
        Calendar calendar = Calendar.getInstance(); 
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd"); 
        String formattedDate = sdf.format(calendar.getTime()); 
        
        lblStartDate.setText(formattedDate);
       setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
    }
    
    public void setCustomer(Customer customer) {
        this.customer = customer;
        if (customer != null) {
            lblCustomerName.setText(customer.getName());
            lblCustomerId.setText(customer.getCustomerId());
            lblEmail.setText(customer.getEmail());
            lblPhoneNumber.setText(customer.getPhoneNumber());
            lblRuc.setText(customer.getRuc());
            lblCustomerAdress.setText(customer.getAddress());
        }
    }
    
    public void changelblName(Customer customer){
            if (customer != null) {
            lblCustomerName.setText(customer.getName());
            lblCustomerId.setText(customer.getCustomerId());
            lblEmail.setText(customer.getEmail());
            lblPhoneNumber.setText(customer.getPhoneNumber());
            lblRuc.setText(customer.getRuc());
            lblCustomerAdress.setText(customer.getAddress());
        } else {
            lblCustomerName.setText("No customer selected");
            lblCustomerId.setText("");
            lblEmail.setText("");
            lblPhoneNumber.setText("");
            lblRuc.setText("");
            lblCustomerAdress.setText("");
        }
    }
    
    
       
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        txtAddress = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        txtRuc = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtPhoneNumber = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        bgCustomerOption = new javax.swing.ButtonGroup();
        bgInvoiced = new javax.swing.ButtonGroup();
        bgPaided = new javax.swing.ButtonGroup();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtProjectTitle = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtpDescription = new javax.swing.JTextPane();
        jLabel10 = new javax.swing.JLabel();
        rbtnCustomerOptionYes = new javax.swing.JRadioButton();
        rbnCreateNewCustomer = new javax.swing.JRadioButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        lblRuc = new javax.swing.JLabel();
        lblCustomerName = new javax.swing.JLabel();
        lblCustomerAdress = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        lblPhoneNumber = new javax.swing.JLabel();
        btnCustomerChoose = new javax.swing.JButton();
        lblCustomerId = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        lblStartDate = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        dcrCloseDate = new com.toedter.calendar.JDateChooser();
        jLabel21 = new javax.swing.JLabel();
        txtQuote = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        cmbQuoteStatus = new javax.swing.JComboBox<>();
        jLabel23 = new javax.swing.JLabel();
        rbtnInvoiced = new javax.swing.JRadioButton();
        rbtnNotInvoiced = new javax.swing.JRadioButton();
        jpIsPaided = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        rbtnPaid = new javax.swing.JRadioButton();
        rbtnNotPaid = new javax.swing.JRadioButton();
        jLabel25 = new javax.swing.JLabel();
        cmbSector = new javax.swing.JComboBox<>();
        btnProyectSave = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        jLabel5.setFont(new java.awt.Font("Book Antiqua", 1, 14)); // NOI18N
        jLabel5.setText("Ingrese su Dirección");

        jLabel6.setFont(new java.awt.Font("Book Antiqua", 1, 14)); // NOI18N
        jLabel6.setText("Ingrese su número de cedula");

        jLabel7.setFont(new java.awt.Font("Book Antiqua", 1, 14)); // NOI18N
        jLabel7.setText("Ingrese el nombre del cliente/empresa");

        txtName.setToolTipText("Ingrese el nombre del cliente/empresa");

        jLabel2.setFont(new java.awt.Font("Book Antiqua", 1, 14)); // NOI18N
        jLabel2.setText("Ingrese el RUC:");

        txtId.setToolTipText("Ingrese el numero de cédula");

        txtRuc.setToolTipText("Ingrese su RUC");

        jLabel3.setFont(new java.awt.Font("Book Antiqua", 1, 14)); // NOI18N
        jLabel3.setText("Ingrese un número de contacto");

        txtPhoneNumber.setToolTipText("Ingrese numero de telefono");

        jLabel4.setFont(new java.awt.Font("Book Antiqua", 1, 14)); // NOI18N
        jLabel4.setText("Ingrese un e-mail");

        txtEmail.setToolTipText("Ingrese su email");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Insertar Proyecto");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(423, 423, 423)
                .addComponent(jLabel8)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );

        jLabel1.setText("Ingrese el título del proyecto:");

        jLabel9.setText("Ingrese una descripción:");

        txtProjectTitle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtProjectTitleActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(txtpDescription);

        jLabel10.setText("Datos del Cliente");

        rbtnCustomerOptionYes.setText("Selecionar Cliente");
        rbtnCustomerOptionYes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnCustomerOptionYesActionPerformed(evt);
            }
        });

        rbnCreateNewCustomer.setText("Crear Nuevo Cliente");
        rbnCreateNewCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbnCreateNewCustomerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(txtProjectTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 482, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(33, 33, 33)
                        .addComponent(rbtnCustomerOptionYes, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rbnCreateNewCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(42, 42, 42)
                        .addComponent(jScrollPane1)))
                .addContainerGap(401, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtProjectTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rbtnCustomerOptionYes)
                    .addComponent(rbnCreateNewCustomer))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel11.setText("Datos ");

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel12.setText("Dirección:");

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel13.setText("Nombre:");

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel14.setText("RUC:");

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel15.setText("Código del comprador: ");

        lblRuc.setText(".");

        lblCustomerName.setText(".");

        lblCustomerAdress.setText(".");

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel16.setText("Teléfono:");

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel17.setText("E-mail");

        lblEmail.setText(".");

        lblPhoneNumber.setText(".");

        btnCustomerChoose.setText("Volver a Escoger");
        btnCustomerChoose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCustomerChooseActionPerformed(evt);
            }
        });

        lblCustomerId.setText(".");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel14)
                            .addComponent(jLabel15)
                            .addComponent(jLabel13)
                            .addComponent(jLabel12)
                            .addComponent(jLabel17)
                            .addComponent(jLabel16))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblPhoneNumber, javax.swing.GroupLayout.DEFAULT_SIZE, 320, Short.MAX_VALUE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblRuc, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblCustomerName, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblCustomerAdress, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblCustomerId, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addGap(575, 575, 575))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCustomerChoose)
                .addGap(30, 30, 30))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(lblCustomerId, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(lblRuc))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(lblCustomerName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(lblCustomerAdress))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(lblEmail))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(lblPhoneNumber))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCustomerChoose)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel18.setText("Fecha de creación: ");

        lblStartDate.setText("StartDate");

        jLabel20.setText("Fecha de cierre: ");

        jLabel21.setText("Presupuesto:");

        txtQuote.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtQuoteActionPerformed(evt);
            }
        });

        jLabel22.setText("Estado de Presupuesto:");

        cmbQuoteStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Enviado", "Rechazado", "Aceptado", " " }));
        cmbQuoteStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbQuoteStatusActionPerformed(evt);
            }
        });

        jLabel23.setText("Facturado:");

        rbtnInvoiced.setText("Sí");
        rbtnInvoiced.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnInvoicedActionPerformed(evt);
            }
        });

        rbtnNotInvoiced.setText("No");
        rbtnNotInvoiced.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnNotInvoicedActionPerformed(evt);
            }
        });

        jLabel24.setText("Pagado:");

        rbtnPaid.setText("Sí");
        rbtnPaid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnPaidActionPerformed(evt);
            }
        });

        rbtnNotPaid.setText("No");
        rbtnNotPaid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnNotPaidActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpIsPaidedLayout = new javax.swing.GroupLayout(jpIsPaided);
        jpIsPaided.setLayout(jpIsPaidedLayout);
        jpIsPaidedLayout.setHorizontalGroup(
            jpIsPaidedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpIsPaidedLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addComponent(rbtnPaid, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addComponent(rbtnNotPaid, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );
        jpIsPaidedLayout.setVerticalGroup(
            jpIsPaidedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpIsPaidedLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jpIsPaidedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(rbtnPaid)
                    .addComponent(rbtnNotPaid))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        jLabel25.setText("Sector:");

        cmbSector.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Público", "Privado", " " }));
        cmbSector.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbSectorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel18)
                            .addComponent(jLabel20)
                            .addComponent(jLabel21))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(lblStartDate, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(226, 226, 226)
                                .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(rbtnInvoiced, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(41, 41, 41)
                                .addComponent(rbtnNotInvoiced, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtQuote, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(dcrCloseDate, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(96, 96, 96)
                                .addComponent(jpIsPaided, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel22))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cmbQuoteStatus, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cmbSector, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(209, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(lblStartDate)
                    .addComponent(jLabel23)
                    .addComponent(rbtnInvoiced)
                    .addComponent(rbtnNotInvoiced))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(dcrCloseDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel21)
                            .addComponent(txtQuote, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jpIsPaided, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(cmbQuoteStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(cmbSector, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        btnProyectSave.setText("Guardar");
        btnProyectSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProyectSaveActionPerformed(evt);
            }
        });

        jButton1.setText("Regresar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnProyectSave)
                .addGap(26, 26, 26))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnProyectSave)
                    .addComponent(jButton1))
                .addContainerGap(7, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtProjectTitleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtProjectTitleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtProjectTitleActionPerformed

    private void rbtnCustomerOptionYesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnCustomerOptionYesActionPerformed
       
        if (rbtnCustomerOptionYes.isSelected()) {
            LoadCustomerFrm customerFrame = new LoadCustomerFrm(this);
            customerFrame.setVisible(true);
            jPanel3.setVisible(true);  
        } else {
            jPanel3.setVisible(false);  

            lblCustomerName.setText("");
            lblCustomerId.setText("");
            lblEmail.setText("");
            lblPhoneNumber.setText("");
            lblRuc.setText("");
            lblCustomerAdress.setText("");
            customer = null;
        }
    }//GEN-LAST:event_rbtnCustomerOptionYesActionPerformed

    private void txtQuoteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtQuoteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtQuoteActionPerformed

    private void rbtnInvoicedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnInvoicedActionPerformed
        if (rbtnInvoiced.isSelected()) {
            rbtnInvoiced.setSelected(true);
            rbtnNotInvoiced.setSelected(false); 
        }
    }//GEN-LAST:event_rbtnInvoicedActionPerformed

    private void rbtnPaidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnPaidActionPerformed
        if (rbtnPaid.isSelected()) {
            rbtnPaid.setSelected(true);
            rbtnNotPaid.setSelected(false); 
        }
    }//GEN-LAST:event_rbtnPaidActionPerformed

    private void btnProyectSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProyectSaveActionPerformed
        
        
        if (customer == null) {
            JOptionPane.showMessageDialog(this, "Por favor, seleccione un cliente antes de guardar el proyecto.", "Advertencia", JOptionPane.WARNING_MESSAGE);
            return;
        }

       
        Random random = new Random();
        String projectId = String.format("%05d", random.nextInt(100000)); 

        
        String projectTitle = txtProjectTitle.getText().trim();
        String projectDescription = txtpDescription.getText().trim(); 
        Customer customerInfo = customer; 
        Date startDate = new Date();  
        Date closingDate = (dcrCloseDate.getDate() != null) ? dcrCloseDate.getDate() : null;  

        
        double startquote = 0;
        try {
            startquote = Double.parseDouble(txtQuote.getText().trim());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Por favor, ingrese un presupuesto válido.", "Error", JOptionPane.ERROR_MESSAGE);
            return;  
        }

        
        ProjectStatus operationalStatus = ProjectStatus.CREATED; 

        
        String selectedStatus = cmbQuoteStatus.getSelectedItem().toString().trim();
        if (selectedStatus.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Por favor, seleccione un estado de cotización.", "Advertencia", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        ProjectStatus quoteStatus = ProjectStatus.fromString(selectedStatus);

       
        boolean invoiced = rbtnInvoiced.isSelected();
        boolean paid = rbtnPaid.isSelected();

        
        boolean isPublic = cmbSector.getSelectedItem().toString().equals("Público");

       
        Project project = new Project(projectTitle, projectId, projectDescription, customerInfo, startDate, closingDate, 
                                      startquote, operationalStatus, quoteStatus, paid, invoiced, isPublic);

        try {
                projectController.save(project);
                JOptionPane.showMessageDialog(this, "Proyecto crado correctamente.", "Éxito", JOptionPane.INFORMATION_MESSAGE);
                clearFields();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Error al guardar el cliente: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_btnProyectSaveActionPerformed
    private void clearFields() {
        
        txtProjectTitle.setText("");
        txtpDescription.setText("");
        txtQuote.setText("");

        
        cmbQuoteStatus.setSelectedIndex(0);  

       
        rbtnInvoiced.setSelected(false);
        rbtnPaid.setSelected(false);

       
        cmbSector.setSelectedIndex(0);  

       
        dcrCloseDate.setDate(null); 
    }
    private void cmbQuoteStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbQuoteStatusActionPerformed
     
    }//GEN-LAST:event_cmbQuoteStatusActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose(); 
        if(mainMenu != null) {
            mainMenu.setVisible(true);  
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void cmbSectorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbSectorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbSectorActionPerformed

    private void btnCustomerChooseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCustomerChooseActionPerformed
        if (rbtnCustomerOptionYes.isSelected()) {
            LoadCustomerFrm loadCustomerFrm = new LoadCustomerFrm(this);
            loadCustomerFrm.setVisible(true);
        } else if (rbnCreateNewCustomer.isSelected()) {

            AddClientforProjectFrm addClientforProjectFrm = new AddClientforProjectFrm(this);
            addClientforProjectFrm.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(this, "Por favor, seleccione una opción antes de continuar.", "Advertencia", JOptionPane.WARNING_MESSAGE);
        }
       
    }//GEN-LAST:event_btnCustomerChooseActionPerformed

    private void rbnCreateNewCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbnCreateNewCustomerActionPerformed
        if (rbnCreateNewCustomer.isSelected()) {
            AddClientforProjectFrm addClientforProjectFrm =  new AddClientforProjectFrm(this) ;
            addClientforProjectFrm.setVisible(true);
            jPanel3.setVisible(true);
        } else {
            jPanel3.setVisible(false);

            lblCustomerName.setText("");
            lblCustomerId.setText("");
            lblEmail.setText("");
            lblPhoneNumber.setText("");
            lblRuc.setText("");
            lblCustomerAdress.setText("");
            customer = null;
        }
        
    }//GEN-LAST:event_rbnCreateNewCustomerActionPerformed

    private void rbtnNotInvoicedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnNotInvoicedActionPerformed
        if (rbtnNotInvoiced.isSelected()) {
            rbtnNotInvoiced.setSelected(true);
            rbtnInvoiced.setSelected(false); 
        }
    }//GEN-LAST:event_rbtnNotInvoicedActionPerformed

    private void rbtnNotPaidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnNotPaidActionPerformed
        if (rbtnNotPaid.isSelected()) {
            rbtnNotPaid.setSelected(true);
            rbtnPaid.setSelected(false); 
        }
    }//GEN-LAST:event_rbtnNotPaidActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddProjectFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddProjectFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddProjectFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddProjectFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddProjectFrm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bgCustomerOption;
    private javax.swing.ButtonGroup bgInvoiced;
    private javax.swing.ButtonGroup bgPaided;
    private javax.swing.JButton btnCustomerChoose;
    private javax.swing.JButton btnProyectSave;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cmbQuoteStatus;
    private javax.swing.JComboBox<String> cmbSector;
    private com.toedter.calendar.JDateChooser dcrCloseDate;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel jpIsPaided;
    private javax.swing.JLabel lblCustomerAdress;
    private javax.swing.JLabel lblCustomerId;
    private javax.swing.JLabel lblCustomerName;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblPhoneNumber;
    private javax.swing.JLabel lblRuc;
    private javax.swing.JLabel lblStartDate;
    private javax.swing.JRadioButton rbnCreateNewCustomer;
    private javax.swing.JRadioButton rbtnCustomerOptionYes;
    private javax.swing.JRadioButton rbtnInvoiced;
    private javax.swing.JRadioButton rbtnNotInvoiced;
    private javax.swing.JRadioButton rbtnNotPaid;
    private javax.swing.JRadioButton rbtnPaid;
    private javax.swing.JTextField txtAddress;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPhoneNumber;
    private javax.swing.JTextField txtProjectTitle;
    private javax.swing.JTextField txtQuote;
    private javax.swing.JTextField txtRuc;
    private javax.swing.JTextPane txtpDescription;
    // End of variables declaration//GEN-END:variables
}
