/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ec.edu.espe.stockbill.view;


/**
 *
 * @author Lucas Gongora
 */
public class FrmAdministrator extends javax.swing.JFrame {

    /**
     * Creates new form Administrator
     */
    public FrmAdministrator() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu9 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        pnlTitle = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        pnlBody = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        pnlFooter = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu11 = new javax.swing.JMenu();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenu12 = new javax.swing.JMenu();
        jMenuItem11 = new javax.swing.JMenuItem();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenuItem12 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        mnAddProduct = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        mnItemConvertUnits = new javax.swing.JMenuItem();
        mnItemAddConversion = new javax.swing.JMenuItem();
        mnItemUpdateConversion = new javax.swing.JMenuItem();
        mnItemDeleteSubUnit = new javax.swing.JMenuItem();
        mnItemDeleteUnit = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        jMenu7 = new javax.swing.JMenu();
        mnItemAddCustomer = new javax.swing.JMenuItem();
        mnItemUpdateCustomer = new javax.swing.JMenuItem();
        mnItemViewCustomers = new javax.swing.JMenuItem();
        mnItemDeleteCustomer = new javax.swing.JMenuItem();
        mntItemAddSupplier = new javax.swing.JMenu();
        mnItemAddSupplier = new javax.swing.JMenuItem();
        mnItemUpdateSupplier = new javax.swing.JMenuItem();
        mnItemViewSuppliers = new javax.swing.JMenuItem();
        mnItemDeleteSupplier = new javax.swing.JMenuItem();
        jMenu10 = new javax.swing.JMenu();

        jMenu9.setText("jMenu9");

        jMenuItem1.setText("jMenuItem1");

        jMenuItem4.setText("jMenuItem4");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel4.setText("Sistema Integral de Facturación e Inventarios con Conversión de Unidades");

        javax.swing.GroupLayout pnlTitleLayout = new javax.swing.GroupLayout(pnlTitle);
        pnlTitle.setLayout(pnlTitleLayout);
        pnlTitleLayout.setHorizontalGroup(
            pnlTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTitleLayout.createSequentialGroup()
                .addGap(247, 247, 247)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 809, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlTitleLayout.setVerticalGroup(
            pnlTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTitleLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\Lucas\\Desktop\\Carrera\\segundo-tercer-semestre\\POO\\proyecto\\ESPE2410-OOPSW1973-NightmareSquad\\06-Code\\GUI\\AccountingSystem\\src\\main\\java\\images\\logo.jpg")); // NOI18N

        javax.swing.GroupLayout pnlBodyLayout = new javax.swing.GroupLayout(pnlBody);
        pnlBody.setLayout(pnlBodyLayout);
        pnlBodyLayout.setHorizontalGroup(
            pnlBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBodyLayout.createSequentialGroup()
                .addGap(200, 200, 200)
                .addComponent(jLabel3)
                .addContainerGap(117, Short.MAX_VALUE))
        );
        pnlBodyLayout.setVerticalGroup(
            pnlBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBodyLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jLabel1.setText("StockBill Software");

        javax.swing.GroupLayout pnlFooterLayout = new javax.swing.GroupLayout(pnlFooter);
        pnlFooter.setLayout(pnlFooterLayout);
        pnlFooterLayout.setHorizontalGroup(
            pnlFooterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFooterLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlFooterLayout.setVerticalGroup(
            pnlFooterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlFooterLayout.createSequentialGroup()
                .addContainerGap(43, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(41, 41, 41))
        );

        jMenu1.setText("Billing");

        jMenu11.setText("Venta");

        jMenuItem8.setText("Datos del cliente");
        jMenu11.add(jMenuItem8);

        jMenuItem7.setText("Datos de los productos");
        jMenu11.add(jMenuItem7);

        jMenuItem9.setText("Generar comprobante");
        jMenu11.add(jMenuItem9);

        jMenu1.add(jMenu11);

        jMenu12.setText("Purchase");

        jMenuItem11.setText("Añadir proveedor");
        jMenu12.add(jMenuItem11);

        jMenuItem10.setText("Añadir Producto");
        jMenu12.add(jMenuItem10);

        jMenuItem12.setText("Generar comprobante");
        jMenuItem12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem12ActionPerformed(evt);
            }
        });
        jMenu12.add(jMenuItem12);

        jMenu1.add(jMenu12);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Inventory");

        mnAddProduct.setText("Añadir");
        jMenu2.add(mnAddProduct);

        jMenuItem5.setText("Eliminar");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem5);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Transactions");
        jMenuBar1.add(jMenu3);

        jMenu4.setText("Conversión");

        mnItemConvertUnits.setText("Convertir unidades");
        mnItemConvertUnits.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnItemConvertUnitsActionPerformed(evt);
            }
        });
        jMenu4.add(mnItemConvertUnits);

        mnItemAddConversion.setText("Añadir");
        mnItemAddConversion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnItemAddConversionActionPerformed(evt);
            }
        });
        jMenu4.add(mnItemAddConversion);

        mnItemUpdateConversion.setText("Actualizar");
        mnItemUpdateConversion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnItemUpdateConversionActionPerformed(evt);
            }
        });
        jMenu4.add(mnItemUpdateConversion);

        mnItemDeleteSubUnit.setText("Eliminar valor de conversión");
        mnItemDeleteSubUnit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnItemDeleteSubUnitActionPerformed(evt);
            }
        });
        jMenu4.add(mnItemDeleteSubUnit);

        mnItemDeleteUnit.setText("Eliminar conversiones de una unidad");
        mnItemDeleteUnit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnItemDeleteUnitActionPerformed(evt);
            }
        });
        jMenu4.add(mnItemDeleteUnit);

        jMenuBar1.add(jMenu4);

        jMenu5.setText("Branches");

        jMenuItem2.setText("Añadir");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem2);

        jMenuItem3.setText("Eliminar");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem3);

        jMenuItem6.setText("Actualizar");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem6);

        jMenuBar1.add(jMenu5);

        jMenu6.setText("Vouchers");
        jMenuBar1.add(jMenu6);

        jMenu7.setText("Cliente");

        mnItemAddCustomer.setText("Añadir");
        mnItemAddCustomer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mnItemAddCustomerMouseClicked(evt);
            }
        });
        mnItemAddCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnItemAddCustomerActionPerformed(evt);
            }
        });
        jMenu7.add(mnItemAddCustomer);

        mnItemUpdateCustomer.setText("Actualizar");
        mnItemUpdateCustomer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mnItemUpdateCustomerMouseClicked(evt);
            }
        });
        mnItemUpdateCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnItemUpdateCustomerActionPerformed(evt);
            }
        });
        jMenu7.add(mnItemUpdateCustomer);

        mnItemViewCustomers.setText("Mostrar");
        mnItemViewCustomers.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mnItemViewCustomersMouseClicked(evt);
            }
        });
        mnItemViewCustomers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnItemViewCustomersActionPerformed(evt);
            }
        });
        jMenu7.add(mnItemViewCustomers);

        mnItemDeleteCustomer.setText("Eliminar");
        mnItemDeleteCustomer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mnItemDeleteCustomerMouseClicked(evt);
            }
        });
        mnItemDeleteCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnItemDeleteCustomerActionPerformed(evt);
            }
        });
        jMenu7.add(mnItemDeleteCustomer);

        jMenuBar1.add(jMenu7);

        mntItemAddSupplier.setText("Proveedor");

        mnItemAddSupplier.setText("Añadir");
        mnItemAddSupplier.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mnItemAddSupplierMouseClicked(evt);
            }
        });
        mnItemAddSupplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnItemAddSupplierActionPerformed(evt);
            }
        });
        mntItemAddSupplier.add(mnItemAddSupplier);

        mnItemUpdateSupplier.setText("Actualizar");
        mnItemUpdateSupplier.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mnItemUpdateSupplierMouseClicked(evt);
            }
        });
        mnItemUpdateSupplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnItemUpdateSupplierActionPerformed(evt);
            }
        });
        mntItemAddSupplier.add(mnItemUpdateSupplier);

        mnItemViewSuppliers.setText("Mostrar");
        mnItemViewSuppliers.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mnItemViewSuppliersMouseClicked(evt);
            }
        });
        mnItemViewSuppliers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnItemViewSuppliersActionPerformed(evt);
            }
        });
        mntItemAddSupplier.add(mnItemViewSuppliers);

        mnItemDeleteSupplier.setText("Eliminar");
        mnItemDeleteSupplier.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mnItemDeleteSupplierMouseClicked(evt);
            }
        });
        mnItemDeleteSupplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnItemDeleteSupplierActionPerformed(evt);
            }
        });
        mntItemAddSupplier.add(mnItemDeleteSupplier);

        jMenuBar1.add(mntItemAddSupplier);

        jMenu10.setText("Exit");
        jMenu10.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jMenu10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu10MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu10);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlBody, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlFooter, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlBody, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pnlFooter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenu10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu10MouseClicked
        FrmLogin frmLogin = new FrmLogin();
        frmLogin.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jMenu10MouseClicked

    private void mnItemAddCustomerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnItemAddCustomerMouseClicked

    }//GEN-LAST:event_mnItemAddCustomerMouseClicked

    private void mnItemUpdateCustomerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnItemUpdateCustomerMouseClicked

    }//GEN-LAST:event_mnItemUpdateCustomerMouseClicked

    private void mnItemViewCustomersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnItemViewCustomersMouseClicked


    }//GEN-LAST:event_mnItemViewCustomersMouseClicked

    private void mnItemDeleteCustomerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnItemDeleteCustomerMouseClicked


    }//GEN-LAST:event_mnItemDeleteCustomerMouseClicked

    private void mnItemAddSupplierMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnItemAddSupplierMouseClicked

    }//GEN-LAST:event_mnItemAddSupplierMouseClicked

    private void mnItemUpdateSupplierMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnItemUpdateSupplierMouseClicked

    }//GEN-LAST:event_mnItemUpdateSupplierMouseClicked

    private void mnItemViewSuppliersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnItemViewSuppliersMouseClicked

    }//GEN-LAST:event_mnItemViewSuppliersMouseClicked

    private void mnItemDeleteSupplierMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnItemDeleteSupplierMouseClicked

    }//GEN-LAST:event_mnItemDeleteSupplierMouseClicked

    private void mnItemAddCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnItemAddCustomerActionPerformed
        FrmCustomerAddition frmCustomerAddition = new FrmCustomerAddition();
        frmCustomerAddition.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_mnItemAddCustomerActionPerformed

    private void mnItemUpdateCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnItemUpdateCustomerActionPerformed
        FrmCustomerUpdating frmCustomerUpdating = new FrmCustomerUpdating();
        frmCustomerUpdating.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_mnItemUpdateCustomerActionPerformed

    private void mnItemViewCustomersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnItemViewCustomersActionPerformed
        System.out.println("Holaaaaa");
        FrmCustomerView frmCustomerView = new FrmCustomerView();
        frmCustomerView.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_mnItemViewCustomersActionPerformed

    private void mnItemDeleteCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnItemDeleteCustomerActionPerformed
        
    }//GEN-LAST:event_mnItemDeleteCustomerActionPerformed

    private void mnItemAddSupplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnItemAddSupplierActionPerformed
       
    }//GEN-LAST:event_mnItemAddSupplierActionPerformed

    private void mnItemUpdateSupplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnItemUpdateSupplierActionPerformed
        
    }//GEN-LAST:event_mnItemUpdateSupplierActionPerformed

    private void mnItemViewSuppliersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnItemViewSuppliersActionPerformed
        
    }//GEN-LAST:event_mnItemViewSuppliersActionPerformed

    private void mnItemDeleteSupplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnItemDeleteSupplierActionPerformed
        
    }//GEN-LAST:event_mnItemDeleteSupplierActionPerformed

    private void mnItemUpdateConversionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnItemUpdateConversionActionPerformed
        FrmConversionUpdating frmConversionUpdating = new FrmConversionUpdating();
        frmConversionUpdating.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_mnItemUpdateConversionActionPerformed

    private void mnItemAddConversionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnItemAddConversionActionPerformed
        FrmConversionAddition frmConversionAddition = new FrmConversionAddition();
        frmConversionAddition.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_mnItemAddConversionActionPerformed

    private void mnItemConvertUnitsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnItemConvertUnitsActionPerformed
        FrmConverterUnits frmConverterUnits = new FrmConverterUnits();
        frmConverterUnits.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_mnItemConvertUnitsActionPerformed

    private void mnItemDeleteSubUnitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnItemDeleteSubUnitActionPerformed
        FrmFinalUnitElimination frmFinalUnitElimination = new FrmFinalUnitElimination();
        frmFinalUnitElimination.setVisible(true);
        
        this.setVisible(false);
    }//GEN-LAST:event_mnItemDeleteSubUnitActionPerformed

    private void mnItemDeleteUnitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnItemDeleteUnitActionPerformed
       FrmSourceUnitElimination frmSourceUnitElimination;
       frmSourceUnitElimination = new FrmSourceUnitElimination();
       frmSourceUnitElimination.setVisible(true);
       this.setVisible(false);
    }//GEN-LAST:event_mnItemDeleteUnitActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        FrmBranchAddition frmBranchAddition;
        frmBranchAddition = new FrmBranchAddition();
        
        frmBranchAddition.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        FrmBranchElimination frmBranchElimination = new FrmBranchElimination();
        frmBranchElimination.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        FrmInventoryElimination frmInventoryElimination = new FrmInventoryElimination();
        frmInventoryElimination.setVisible(true);
        this.setVisible(false);
                
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
       FrmBranchUpdating frmBranchUpdating = new FrmBranchUpdating();
       frmBranchUpdating.setVisible(true);
       this.setVisible(false);
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem12ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmAdministrator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmAdministrator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmAdministrator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmAdministrator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmAdministrator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu10;
    private javax.swing.JMenu jMenu11;
    private javax.swing.JMenu jMenu12;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JMenuItem mnAddProduct;
    private javax.swing.JMenuItem mnItemAddConversion;
    private javax.swing.JMenuItem mnItemAddCustomer;
    private javax.swing.JMenuItem mnItemAddSupplier;
    private javax.swing.JMenuItem mnItemConvertUnits;
    private javax.swing.JMenuItem mnItemDeleteCustomer;
    private javax.swing.JMenuItem mnItemDeleteSubUnit;
    private javax.swing.JMenuItem mnItemDeleteSupplier;
    private javax.swing.JMenuItem mnItemDeleteUnit;
    private javax.swing.JMenuItem mnItemUpdateConversion;
    private javax.swing.JMenuItem mnItemUpdateCustomer;
    private javax.swing.JMenuItem mnItemUpdateSupplier;
    private javax.swing.JMenuItem mnItemViewCustomers;
    private javax.swing.JMenuItem mnItemViewSuppliers;
    private javax.swing.JMenu mntItemAddSupplier;
    private javax.swing.JPanel pnlBody;
    private javax.swing.JPanel pnlFooter;
    private javax.swing.JPanel pnlTitle;
    // End of variables declaration//GEN-END:variables
}
