/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ec.edu.espe.stockbill.view;

import ec.edu.espe.stockbill.controller.ConversionController;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Lucas Gongora
 */
public class FrmConversionUpdating extends javax.swing.JFrame {

    ConversionController conversionController;

    /**
     * Creates new form FrmConversionUpdating
     */
    public FrmConversionUpdating() {
        initComponents();
        conversionController = new ConversionController();
        for (String sourceUnit : this.conversionController.getSourceUnits()) {
            cmbxSourceUnit.addItem(sourceUnit);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        cmbxSourceUnit = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        cmbxDestinyUnit = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        txtNewValueOfFinalUnit = new javax.swing.JTextField();
        btnUpdate = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Escoge una unidad de origen");

        cmbxSourceUnit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbxSourceUnitActionPerformed(evt);
            }
        });

        jLabel2.setText("Ecoge la unidad destino que quieres modificar");

        cmbxDestinyUnit.setEnabled(false);
        cmbxDestinyUnit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbxDestinyUnitActionPerformed(evt);
            }
        });

        jLabel3.setText("Cambia el factor de conversión: ");

        btnUpdate.setText("Actualizar");
        btnUpdate.setEnabled(false);
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setText("Actualizar conversión");

        jMenu1.setText("Return main menu");
        jMenu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu1MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(84, 84, 84)))
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(cmbxSourceUnit, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(cmbxDestinyUnit, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtNewValueOfFinalUnit, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(108, 108, 108))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnUpdate)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(145, 145, 145))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cmbxSourceUnit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cmbxDestinyUnit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtNewValueOfFinalUnit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 67, Short.MAX_VALUE)
                .addComponent(btnUpdate)
                .addGap(32, 32, 32))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenu1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu1MouseClicked
        FrmAdministrator frmAdministrator = new FrmAdministrator();
        frmAdministrator.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jMenu1MouseClicked

    private void cmbxSourceUnitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbxSourceUnitActionPerformed
        cmbxDestinyUnit.removeAllItems();
        String sourceUnit = cmbxSourceUnit.getSelectedItem() != null ? cmbxSourceUnit.getSelectedItem().toString() : "";

        if (!sourceUnit.isEmpty()) {
            for (String finalUnit : this.conversionController.getFinalUnits(sourceUnit)) {
                boolean existFinalUnit = ((DefaultComboBoxModel<String>) cmbxDestinyUnit.getModel()).getIndexOf(finalUnit) != -1;
                if (!existFinalUnit) {
                    cmbxDestinyUnit.addItem(finalUnit);
                }
            }

            cmbxDestinyUnit.setEnabled(true);
        } else {
            cmbxDestinyUnit.setEnabled(false);
        }

        checkAndEnableUpdateButton();
    }//GEN-LAST:event_cmbxSourceUnitActionPerformed

    private void cmbxDestinyUnitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbxDestinyUnitActionPerformed
        checkAndEnableUpdateButton();

        String sourceUnit = cmbxSourceUnit.getSelectedItem() != null ? cmbxSourceUnit.getSelectedItem().toString() : "";
        String finalUnit = cmbxDestinyUnit.getSelectedItem() != null ? cmbxDestinyUnit.getSelectedItem().toString() : "";

        if (!sourceUnit.isEmpty() && !finalUnit.isEmpty()) {
            String conversionFactor = String.valueOf(conversionController.getConversionFactor(sourceUnit, finalUnit));
            txtNewValueOfFinalUnit.setText(conversionFactor);
        }

    }//GEN-LAST:event_cmbxDestinyUnitActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        String sourceUnit;
        String finalUnit;
        String newConversionFactor;
        boolean isConversionUpdated;

        sourceUnit = cmbxSourceUnit.getSelectedItem().toString();
        finalUnit = cmbxDestinyUnit.getSelectedItem().toString();
        newConversionFactor = txtNewValueOfFinalUnit.getText();
        isConversionUpdated = conversionController.updateConversion(sourceUnit, finalUnit, newConversionFactor);
        if (isConversionUpdated) {
            JOptionPane.showMessageDialog(rootPane, "La conversion se actualizado correctamente", "Éxito", JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(rootPane, "La conversion no se ha podido actualizar", "Error", JOptionPane.INFORMATION_MESSAGE);
        }


    }//GEN-LAST:event_btnUpdateActionPerformed

    private void checkAndEnableUpdateButton() {
        if (cmbxSourceUnit.getSelectedItem() != null && !cmbxSourceUnit.getSelectedItem().toString().isEmpty()
                && cmbxDestinyUnit.getItemCount() > 0 && cmbxDestinyUnit.getSelectedItem() != null) {
            btnUpdate.setEnabled(true);
        } else {
            btnUpdate.setEnabled(false);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmConversionUpdating.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmConversionUpdating.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmConversionUpdating.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmConversionUpdating.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmConversionUpdating().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnUpdate;
    private javax.swing.JComboBox<String> cmbxDestinyUnit;
    private javax.swing.JComboBox<String> cmbxSourceUnit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JTextField txtNewValueOfFinalUnit;
    // End of variables declaration//GEN-END:variables
}
